"""Employee profile change approvals

Revision ID: 99a3ef1c2db4
Revises: 8a557e2ed653
"""
from alembic import op
import sqlalchemy as sa


revision = '99a3ef1c2db4'
down_revision = '8a557e2ed653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_changes',
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('proposed_name', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_changes_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_changes_customer_id'))

    op.drop_table('profile_changes')
    # ### end Alembic commands ###
